name: ATF Nightly Suite

on:
  schedule:
    - cron: "0 23 * * 1-5"  # Triggers every Monday-Friday at 23:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run automation tests
        run: mvn clean install -DciCd=true -Dbrowser=chrome -DsuiteXmlFile=suites/regressionSuite.xml -P CustomSuite
